storage_path_patterns:
  - '(?i)hdfs://[^\s)''"`]+'
  - '(?i)viewfs://[^\s)''"`]+'
  - '(?i)s3a://[^\s)''"`]+'
  - '(?i)s3://[^\s)''"`]+'
  - '(?i)abfss?://[^\s)''"`]+'
  - '(?i)gs://[^\s)''"`]+'
  - '(?i)/user/[^\s)''"`]+'
  - '(?i)/data/[^\s)''"`]+'
