# Key patterns used to detect potential secrets (values will be redacted)
key_name_patterns:
  - "(?i)password"
  - "(?i)passwd"
  - "(?i)pwd"
  - "(?i)secret"
  - "(?i)token"
  - "(?i)api[_-]?key"
  - "(?i)access[_-]?key"
  - "(?i)private[_-]?key"
  - "(?i)client[_-]?secret"
value_patterns:
  - '(?i)Bearer\s+[A-Za-z0-9\-\._~\+\/]+=*'
  - 'eyJ[a-zA-Z0-9_\-]{10,}\.[a-zA-Z0-9_\-]{10,}\.[a-zA-Z0-9_\-]{10,}'  # JWT-like
pem_markers:
  - "-----BEGIN"
